# Generated by Django 4.1.4 on 2023-12-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Event',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=4096, verbose_name='Event Name')),
        #         ('date', models.DateField(auto_now=True, verbose_name='Event happened date')),
        #         ('score', models.FloatField(verbose_name='Event heat value')),
        #     ],
        # ),
    ]
