# Generated by Django 4.1.4 on 2023-12-25 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OSINT_DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, verbose_name='Events Name')),
                ('date', models.DateField(auto_now=True, verbose_name='Events happened date')),
                ('score', models.FloatField(verbose_name='Events heat value')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=4096, verbose_name='keywords')),
                ('date', models.DateField(auto_now=True, verbose_name='The first time of it')),
            ],
        ),
        migrations.CreateModel(
            name='Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, verbose_name='Objects name')),
                ('role', models.IntegerField(verbose_name='The classes of object')),
                ('gender', models.IntegerField(verbose_name='gender of object')),
            ],
        ),
        migrations.CreateModel(
            name='Objects_to_Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object1_id', models.IntegerField()),
                ('object2_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Objects_to_Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_DB.keywords', verbose_name='Keyword ID')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_DB.objects', verbose_name='Object ID')),
            ],
        ),
        migrations.CreateModel(
            name='Events_to_Objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_DB.events')),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_DB.objects')),
            ],
        ),
        migrations.CreateModel(
            name='Events_to_Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_DB.events', verbose_name='Event ID')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OSINT_DB.keywords', verbose_name='Keyword ID')),
            ],
        ),
    ]
