# Generated by Django 4.2.8 on 2023-12-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT_authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
