# Generated by Django 4.2.8 on 2023-12-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT_authenticate', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
