# Generated by Django 4.2.8 on 2023-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OSINT_authenticate', '0006_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='手机号码'),
        ),
        migrations.AlterUniqueTogether(
            name='customuser',
            unique_together={('phone', 'email')},
        ),
    ]
